import "../../css/articleForm.css";

export const metadata = {
  title: "Add Posts",
  description: "Generated by create next app",
};

export default function AddPostslayout({ children }) {
  return <>{children}</>;
}
