import "../css/articleForm.css";

export const metadata = {
  title: "Posts",
  description: "Generated by create next app",
};

export default function Postslayout({ children }) {
  return <>{children}</>;
}
